---
version: "2.4"
services:
  scrutiny:
    image: 'ghcr.io/analogj/scrutiny:master-web@sha256:03170e39e0bdb50fc8a994c10663862f188608d3313ab78f19241de4ddf2e1f6'
    container_name: scrutiny
    labels:
      - traefik.enable=true
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080
      - show.external=true
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=scrutinydb
      - SCRUTINY_NOTIFY_URLS=generic://n8n:5678/webhook/953f6356-9fcf-420e-a3c7-f46295051d18?disabletls=true&template=json
    user: "9001:9001"
    ports:
      - 3200:8080
    volumes:
      - './config:/opt/scrutiny/config'
    restart: 'unless-stopped'
    depends_on:
      - scrutinydb
  scrutinydb:
    image: 'influxdb:2.7'
    container_name: scrutinydb
    user: "9001:9001"
    volumes:
      - './data:/var/lib/influxdb2'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
networks:
  default:
    external: true
    name: ctr-network